#if !defined(CONFIG_H)
#define CONFIG_H

#define FRONT_LIGHT_MIN_BRIGHTNESS 10
#define FRONT_LIGHT_MAX_BRIGHTNESS 255
#define FRONT_LIGHT_STROBE_LOW 5
#define FRONT_BLINK_RATE 500
#define FRONT_LIGHT_PIN 5

#define FRONT_LIGHT_BUTTON_DEBOUNCE 50
#define FRONT_LIGHT_BUTTON_PIN 4

#define REAR_LIGHT_MIN_BRIGHTNESS 10
#define REAR_LIGHT_MAX_BRIGHTNESS 40
#define REAR_LIGHT_STROBE_LOW 5
#define REAR_BLINK_RATE 500
#define REAR_LIGHT_PIN 6

#endif // CONFIG_H)
